#include <stdio.h>
#include <string.h>

// PotatoScript Classic Alpha 0.6.0 Alpha
// The PotatoScript programming language is made by Benji Dial and Warren Galloway.  It is licensed under the Apache license.
// The official PotatoScript Classic GitHub repository is available at <https://github.com/benjidial/PotatoScript-Classic>.

enum asmBits { SIXTEENBIT, THIRTYTWOBIT, SIXTYFOURBIT };
enum os { LINUX, MACOSX, WINDOWS };
enum asmSyntax { GAS, NASM };
enum errorCode { FINE, NOTSUPPORTED, BADCOMMAND };

int main(int argc, char **args) {
  int bittage = SIXTYFOURBIT, os = LINUX, syntax = GAS, comments = 0;
  for (int i = 1; i < argc; i++)
    if (!(strcmp(argv[i], "--help") && strcmp(argv[i], "-h")))
      puts("Command line arguments:\n"
           "  --help (-h) Prints this screen.\n"
           "  One of the following (--64bit is assumed if none):\n"
           "    --16bit   (-16) Specifies to use 16-bit code in an output assembly file.\n"
           "    --32bit   (-32) Specifies to use 32-bit code in an output assembly file.\n"
           "    --64bit   (-64) Specifies to use 64-bit code in an output assembly file.\n"
           "  One of the following (--linux is assumed if none):\n"
           "    --linux   (-l) Specifies to use Linux interrupts in an output assembly file.\n"
           "    --macosx  (-m) Specifies to use Mac OS X interrupts in an output assembly file.\n"
           "    --windows (-w) Specifies to use MS Windows interrupts in an output assembly file.\n"
           "  One of the following (--gas is assumed if none):\n"
           "    --gas     (-g) Specifies to use GAS syntax in an output assembly file.\n"
           "    --nasm    (-n) Specifies to use NASM syntax in an output assembly file.\n"
           "  One of the sollowing (--ignorecomments is assumed if none\n"
           "    --keepcomments   (-kc) Keeps psc comments as asm comments\n"
           "    --ignorecomments (-ic) Ignore psc comments");
    else if (!(strcmp(argv[i], "--16bit") && strcmp(argv[i], "-16")))
      bittage = SIXTEENBIT;
    else if (!(strcmp(argv[i], "--32bit") && strcmp(argv[i], "-32")))
      bittage = THIRTYTWOBIT;
    else if (!(strcmp(argv[i], "--64bit") && strcmp(argv[i], "-64")))
      bittage = SIXTYFOURBIT;
    else if (!(strcmp(argv[i], "--linux") && strcmp(argv[i], "-l")))
      os = LINUX;
    else if (!(strcmp(argv[i], "--macosx") && strcmp(argv[i], "-m")))
      os = MACOSX;
    else if (!(strcmp(argv[i], "--windows") && strcmp(argv[i], "-w")))
      os = WINDOWS;
    else if (!(strcmp(argv[i], "--gas") && strcmp(argv[i], "-g")))
      sytanx = GAS;
    else if (!(strcmp(argv[i], "--nasm") && strcmp(argv[i], "-n")))
      sytanx = NASM;
    else if (!(strcmp(argv[i], "--keepcomments") && strcmp(argv[i], "-kc")))
      comments = 1;
    else if (!(strcmp(argv[i], "--ignorecomments") && strcmp(argv[i], "-ic")))
      comments = 0;
    else
      fprintf(stderr, "Unrecognized argument \"%s\", ignoring\n", argv[i]);
  puts("; Auto-generated by PotatoScript Alpha 0.6.0 Alpha.");
  fputs("; Designed for ", stdout);
  switch (bits) {
   case SIXTEENBIT:
    fputs("16-bit ", stdout);
    break;
   case THIRTYTWOBIT:
    fputs("32-bit ", stdout);
    break;
   case SIXTYFOURBIT:
    fputs("64-bit ", stdout);
  }
  switch (os) {
   case LINUX:
    fputs("Linux with ", stdout);
    break;
   case MACOSX:
    fputs("Mac OS X with ", stdout);
    break;
   case WINDOWS:
    fputs("MS Windows with ", stdout);
  }
  switch (syntax) {
   case GAS:
    puts("GAS syntax.");
    break;
   case NASM:
    puts("NASM syntax.");
  }
  puts("; The PotatoScript programming language is made by Benji Dial and Warren Galloway.  It is licensed under the Apache license.\n; The official PotatoScript Classic GitHub repository is available at <https://github.com/benjidial/PotatoScript-Classic>.");
  switch (syntax) {
   case GAS:
    puts(".text\n  .globl _main");
    break;
   case NASM:
    puts("  global _start\nsection .text");
  }
  return FINE; 
}
