#include <stdio.h>
#include <string.h>

// PotatoScript Classic Alpha 0.6.0 Alpha
// The PotatoScript programming language is made by Benji Dial and Warren Galloway.  It is licensed under the Apache license.
// The official PotatoScript Classic GitHub repository is available at <https://github.com/benjidial/PotatoScript-Classic>.

enum os { LINUX32, LINUX64 };

void expression(char *buffer) {
  if (buffer[0] == '_')
    printf("[_dat%s]", buffer);
  else
    fputs(buffer, stdout);
}

void expression2(char *buffer) {
  char buffer2[128];
  char *buffer2_ptr = buffer2, token = buffer;
  char next;
  while ((next = *(token++)) != ' ')
    *(buffer2_ptr++) = next;
  *buffer2_ptr = '\0';
  expression(buffer2);
  putchar(',');
  putchar(' ');
  expression(token);
}

int main(int argc, char **args) {
  char regpre = 'r', os = LINUX64, comments = 0;
  for (int i = 1; i < argc; i++)
    if (!(strcmp(argv[i], "--help") && strcmp(argv[i], "-h")))
      puts("Command line arguments:\n"
           "  --help (-h) Prints this screen.\n"
           "  Target operating system (--linux64 if none):\n"
           "    --linux32 (-l32) 32-bit Linux\n"
           "    --linux64 (-l64) 64-bit Linux\n"
           "  Comment handling (--ignorecomments if none\n"
           "    --keepcomments   (-kc) Keeps comments\n"
           "    --ignorecomments (-ic) Ignores comments");
    else if (!(strcmp(argv[i], "--linux32") && strcmp(argv[i], "-l32"))) {
      regpre = 'e';
      os = LINUX32;
    }
    else if (!(strcmp(argv[i], "--linux64") && strcmp(argv[i], "-l64"))) {
      regpre = 'r';
      os = LINUX64;
    }
    else if (!(strcmp(argv[i], "--keepcomments") && strcmp(argv[i], "-kc")))
      comments = 1;
    else if (!(strcmp(argv[i], "--ignorecomments") && strcmp(argv[i], "-ic")))
      comments = 0;
    else
      fprintf(stderr, "Unrecognized argument \"%s\", ignoring\n", argv[i]);
  puts("; Auto-generated by PotatoScript Alpha 0.6.0 Alpha.");
  fputs("; Designed for ", stdout);
  switch (os) {
   case LINUX32:
    fputs("32-bit Linux with ", stdout);
    break;
   case LINUX64:
    fputs("64-bit Linux with ", stdout);
  }
  puts("NASM syntax\n; The PotatoScript programming language is made by Benji Dial and Warren Galloway.  It is licensed under the Apache license.\n; The official PotatoScript Classic GitHub repository is available at <https://github.com/benjidial/PotatoScript-Classic>.");
  puts("  global _start\nsection .text");
  char buf[128];
  while (gets(buf) != NULL)
    if (!strncmp("#_ ", buf, 3))
      fputs("  _dat_", stdout);
      char *tok = buf + 3;
      char next;
      while ((next = *(tok++)) != ' ')
        putchar(next);
      switch (os) {
       case LINUX32:
        printf(" dd %s\n", tok);
        break;
       case LINUX64:
        printf(" dq %s\n", tok);
      }
    else if (!strncmp("##", buf, 2) && comments)
      printf(";%s\n", buf + 2);
    else if (!strcmp("#asm", buf))
      while ((gets(buf) != NULL) && !strcmp("#asm", buf))
        puts(buf);
    else if (!strcmp("#dat", buf))
      puts("section .data");
    else if (!strncmp("#do ", buf, 4))
      printf("  call %s\n", buf + 4);
    else if (!strncmp("#end ", buf, 5)) {
      switch (os) {
       case LINUX32:
        fputs("  mov eax, 1\nmov ebx, ", stdout);
        expression(buf + 5);
        puts("\n  int 80h");
        break;
       case LINUX64:
        fputs("  mov rax, 60\n  mov rdi, ", stdout);
        expression(buf + 5);
        puts("\n  syscall");
      }
    }
    else if (!strncmp("#goto ", buf, 6))
      printf("  jmp _label_%s\n", buf + 6);
    else if (!strncmp("#label ", buf, 7))
      printf("_label_%s:\n", buf + 7);
    else if (!strcmp("#ret", buf))
      puts("  ret");
    else if (!strcmp("#start", buf))
      puts("_start:");
    else if (!strncmp("#string ", buf, 8)) {
      fputs("  _dat", stdout);
      char *tok = buf + 8;
      char next;
      while ((next = *(tok++)) != ' ')
        putchar(next);
      printf(" db \"%s\"\n", tok);
    }
    else if (!strncmp(".say ", buf, 5))
      switch (os) {
       case LINUX32:
        printf("  mov eax, 4\n  mov ebx, 1\n  mov ecx, _dat%s\n  mov edx, 0xffff\n  int 80h\n", buf + 5);
        break;
       case LINUX64:
        printf("  mov rax, 1\n  mov rdi, 1\n  mov rsi, _dat%s\n  mov rdx, 0xffffffff\n  syscall\n", buf + 5);
      }
    else if (!strncmp(".listen ", buf, 8))
      ;/*TODO*/
    else if (!strncmp(".add ", buf, 5)) {
      fputs("  add ", stdout);
      expression2(buf + 5);
      putchar('\n');
    }
    else if (!strncmp(".mul ", buf, 5)) {
      fputs("  mul ", stdout);
      expression2(buf + 5);
      putchar('\n');
    }
    else if (!strncmp(".store ", buf, 7)) {
      fputs("  mov ", stdout);
      expression2(buf + 7);
      putchar('\n');
    }
    else
      ;/*TODO*/
  return 0; 
}
